import { Flower } from './types';

export const FLOWERS: Flower[] = [
  { id: 1, name: 'Lavender', imageUrl: 'https://i.imgur.com/4Yf2k0j.png' },
  { id: 2, name: 'Daffodil', imageUrl: 'https://i.imgur.com/GzB3K0y.png' },
  { id: 3, name: 'Tulip', imageUrl: 'https://i.imgur.com/cRTfH3s.png' },
  { id: 4, name: 'Forget-Me-Not', imageUrl: 'https://i.imgur.com/Qk9Y3e3.png' },
  { id: 5, name: 'Calendula', imageUrl: 'https://i.imgur.com/aWTyB7s.png' },
  { id: 6, name: 'Rose', imageUrl: 'https://i.imgur.com/8i2d27p.png' },
  { id: 7, name: 'Sunflower', imageUrl: 'https://i.imgur.com/M06eE5w.png' },
  { id: 8, name: 'Daisy', imageUrl: 'https://i.imgur.com/2m4S0iY.png' },
  { id: 9, name: 'Orchid', imageUrl: 'https://i.imgur.com/JqkL4tW.png' },
  { id: 10, name: 'Lily', imageUrl: 'https://i.imgur.com/bB4S1aX.png' },
  { id: 11, name: 'Peony', imageUrl: 'https://i.imgur.com/jQw5tY7.png' },
  { id: 12, name: 'Marigold', imageUrl: 'https://i.imgur.com/rS2a8kI.png' },
  { id: 13, name: 'Hibiscus', imageUrl: 'https://i.imgur.com/dXRBF5O.png' },
  { id: 14, name: 'Zinnia', imageUrl: 'https://i.imgur.com/9wMf3bJ.png' },
  { id: 15, name: 'Poppy', imageUrl: 'https://i.imgur.com/mXo3a3U.png' },
  { id: 16, name: 'Carnation', imageUrl: 'https://i.imgur.com/eRY8jjt.png' },
  { id: 17, name: 'Pansy', imageUrl: 'https://i.imgur.com/2sA9fSj.png' },
  { id: 18, name: 'Iris', imageUrl: 'https://i.imgur.com/tVfF1d3.png' },
  { id: 19, name: 'Chrysanthemum', imageUrl: 'https://i.imgur.com/fL8a2gD.png' },
  { id: 20, name: 'Gerbera', imageUrl: 'https://i.imgur.com/r1h4zL7.png' },
  { id: 21, name: 'Dahlia', imageUrl: 'https://i.imgur.com/bY3a5vJ.png' },
  { id: 22, name: 'Snapdragon', imageUrl: 'https://i.imgur.com/E0d4o6J.png' },
  { id: 23, name: 'Aster', imageUrl: 'https://i.imgur.com/T5v1eXf.png' },
  { id: 24, name: 'Crocus', imageUrl: 'https://i.imgur.com/v8n0W7x.png' },
  { id: 25, name: 'Bluebell', imageUrl: 'https://i.imgur.com/N7b0l9z.png' },
  { id: 26, name: 'Amaryllis', imageUrl: 'https://i.imgur.com/5g5t1hK.png' },
  { id: 27, name: 'Buttercup', imageUrl: 'https://i.imgur.com/c6u1n7J.png' },
  { id: 28, name: 'Camellia', imageUrl: 'https://i.imgur.com/L4u3v2o.png' },
  { id: 29, name: 'Cherry Blossom', imageUrl: 'https://i.imgur.com/8Q2Rz3s.png' },
  { id: 30, name: 'Clove', imageUrl: 'https://i.imgur.com/o2y8r4t.png' },
  { id: 31, name: 'Foxglove', imageUrl: 'https://i.imgur.com/s6n3g1H.png' },
  { id: 32, name: 'Freesia', imageUrl: 'https://i.imgur.com/P7f0m8s.png' },
  { id: 33, name: 'Gardenia', imageUrl: 'https://i.imgur.com/A6j4g5B.png' },
  { id: 34, name: 'Heather', imageUrl: 'https://i.imgur.com/m4n3o2P.png' },
  { id: 35, name: 'Hyacinth', imageUrl: 'https://i.imgur.com/t8g7h6J.png' },
  { id: 36, name: 'Jasmine', imageUrl: 'https://i.imgur.com/U9o8f7K.png' },
];
